services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: elbiefit-dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -dbPath /data -sharedDb"
    user: root
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
